DATASET:
    NAME: "rgbdgsd"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 8
TRAIN:
    EPOCHS: 100
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    BASE_SIZE: 512
    BACKBONE_PRETRAINED_PATH: "pretrained/v2/pvt_v2_b3.pth"
    MODEL_SAVE_DIR: 'workdirs/rgbdgsd/pvt2_b3'
    APEX: True
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    TEST_MODEL_PATH: "workdirs/rgbdgsd/pvt2_b3/best_model.pth"

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.0001
MODEL:
    MODEL_NAME: "PVTV2"
    BACKBONE: "mit_b3"


AUG:
    CROP: False
